dist: xenial
sudo: required
os: linux
language: cpp

script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -sf /usr/bin/gcc-8 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-8 /usr/bin/g++
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - dpkg-query -L gcc-8 | grep gcov
  - bash ./build.sh

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    update: true
    packages:
      - gcc-8
      - g++-8
      - boost1.67
      - cmake-data
      - cmake
      - valgrind
      - lcov
